import type { Metadata } from "next";
import { LegalLayout, LegalSection } from "@/components/marketing/legal-layout";

export const metadata: Metadata = {
  title: "Privacy Policy — RelayHub",
  description: "How RelayHub collects, uses, and protects your data.",
  alternates: { canonical: "/privacy" },
};

export default function PrivacyPage() {
  return (
    <LegalLayout title="Privacy Policy" updated="August 1, 2026">
      <p>
        This policy explains what information RelayHub, Inc. (&quot;RelayHub,&quot; &quot;we,&quot; &quot;us&quot;) collects
        when you use our webhook and event delivery platform, and how we use, store, and protect it.
      </p>

      <LegalSection title="Information we collect">
        <p>We collect information you provide directly, information generated by your use of the platform, and information collected automatically:</p>
        <ul className="mt-2 flex flex-col gap-1.5 pl-4">
          <li className="list-disc">Account information: name, email address, and hashed password when you register.</li>
          <li className="list-disc">Organization data: endpoints you configure, events you publish, and delivery logs generated by those deliveries.</li>
          <li className="list-disc">Usage data: API request metadata, IP addresses associated with login and administrative actions, and dashboard interaction data used for audit logging.</li>
          <li className="list-disc">Billing information: plan tier and subscription status. Payment card details are handled by our payment processor and are never stored on RelayHub&apos;s servers.</li>
        </ul>
      </LegalSection>

      <LegalSection title="How we use information">
        <p>
          We use collected information to operate the platform: authenticating you, delivering your webhooks, generating
          delivery logs and analytics, enforcing plan limits, sending transactional email (password resets, invitations,
          alerts you&apos;ve configured), and maintaining audit logs for security and account-recovery purposes. We do not
          sell your data to third parties.
        </p>
      </LegalSection>

      <LegalSection title="Data retention">
        <p>
          Delivery logs are retained according to your organization&apos;s plan tier, ranging from 7 days on the Free plan
          to 365 days on Enterprise. Account and audit log data is retained for the lifetime of your account plus a
          reasonable period afterward for legal and security purposes, after which it is deleted.
        </p>
      </LegalSection>

      <LegalSection title="How we protect your data">
        <p>
          Passwords, API keys, and endpoint signing secrets are hashed or encrypted before storage -- we do not store
          them in a form that could be read back out. Access to production data is restricted to engineers who need it to
          operate the platform, and every sensitive account action is written to an audit log.
        </p>
      </LegalSection>

      <LegalSection title="Your rights">
        <p>
          You can access, export, and delete most of your organization&apos;s data directly from the dashboard. For
          requests we don&apos;t yet support in-product -- including full account deletion -- contact us at{" "}
          <a href="mailto:privacy@relayhub.dev" className="text-signal-amber hover:underline">privacy@relayhub.dev</a>, and
          we&apos;ll process the request within a reasonable timeframe.
        </p>
      </LegalSection>

      <LegalSection title="Cookies">
        <p>
          RelayHub uses a small number of strictly necessary cookies and local storage entries for authentication and
          preference persistence (like your dark mode setting). See our{" "}
          <a href="/cookies" className="text-signal-amber hover:underline">Cookie Policy</a> for the full list.
        </p>
      </LegalSection>

      <LegalSection title="Changes to this policy">
        <p>
          We&apos;ll update the date at the top of this page when this policy changes, and for material changes we&apos;ll
          notify account owners by email.
        </p>
      </LegalSection>

      <LegalSection title="Contact">
        <p>
          Questions about this policy: <a href="mailto:privacy@relayhub.dev" className="text-signal-amber hover:underline">privacy@relayhub.dev</a>, or use the{" "}
          <a href="/contact" className="text-signal-amber hover:underline">contact form</a>.
        </p>
      </LegalSection>
    </LegalLayout>
  );
}
